{% set name = "climate4R" %}
{% set version = "2.6.2" %}
{% set build_number = 1 %}
{% set c4renv = load_file_data('climate4r.yaml', from_recipe_dir=True) %}

package:
  name: r-{{ name|lower }}
  version: {{ version }}

build:
  noarch: generic
  number: {{ build_number }}

requirements:
  host:
    - r-base
  run: 
    - r-base
  {% for dep in c4renv['dependencies']%}
    - {{ dep }}
  {% endfor %}

test:
  commands:
    - $R -e "library('transformeR')"           # [not win]
    - "\"%R%\" -e \"library('transformeR')\""  # [win]

about:
  home: https://github.com/SantanderMetGroup/climate4R
  summary: R Framework for Climate Data Access and Post-processing.
  dev_url: https://github.com/SantanderMetGroup/climate4R
  doc_url: https://github.com/SantanderMetGroup/climate4R
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - cofinoa
